#!/usr/bin/env node
// ============================================================================
// PhantomScope — scripts/build-asm.js
// NASM Assembly Build Script
// Compiles all .asm modules to .obj files and runs validation
// ============================================================================

'use strict';

const { execSync, spawnSync } = require('child_process');
const path = require('path');
const fs   = require('fs');

const ROOT      = path.resolve(__dirname, '..');
const ASM_DIR   = path.join(ROOT, 'asm');
const BUILD_DIR = path.join(ROOT, 'build', 'asm-obj');
const PLATFORM  = process.platform;
const ARCH      = process.arch;

if (ARCH !== 'x64') {
  console.error('[ERROR] PhantomScope requires x64 architecture');
  process.exit(1);
}

const FORMAT = PLATFORM === 'win32' ? 'win64' : 'elf64';
const NASM_FLAGS = PLATFORM === 'linux' ? '-DLINUX' : '';

// Ensure output directory exists
fs.mkdirSync(BUILD_DIR, { recursive: true });

// Generate log2 lookup table before assembling entropy_calc.asm
generateLog2LUT();

// Assembly modules per platform
const ASM_MODULES_WIN = [
  'process_enum.asm',
  'syscall_wrapper.asm',
  'md5_engine.asm',
  'entropy_calc.asm',
];

const ASM_MODULES_LIN = [
  'linux_proc.asm',
  'md5_engine.asm',
  'entropy_calc.asm',
];

const modules = PLATFORM === 'win32' ? ASM_MODULES_WIN : ASM_MODULES_LIN;

let success = true;

console.log(`\n[PhantomScope] Building NASM Assembly (${FORMAT})\n`);

for (const mod of modules) {
  const src = path.join(ASM_DIR, mod);
  const obj = path.join(BUILD_DIR, mod.replace('.asm', '.obj'));

  if (!fs.existsSync(src)) {
    console.warn(`[SKIP] ${mod} — file not found`);
    continue;
  }

  const cmd = `nasm -f ${FORMAT} ${NASM_FLAGS} -O2 -o "${obj}" "${src}"`;
  console.log(`[ASM]  ${mod}`);

  const result = spawnSync('nasm', [
    '-f', FORMAT,
    ...(NASM_FLAGS ? NASM_FLAGS.split(' ') : []),
    '-O2',
    '-o', obj,
    src
  ], { stdio: 'pipe', encoding: 'utf8' });

  if (result.status !== 0) {
    console.error(`[FAIL] ${mod}:`);
    if (result.stderr) console.error(result.stderr);
    success = false;
  } else {
    const stat = fs.statSync(obj);
    console.log(`       → ${path.basename(obj)} (${stat.size} bytes)`);
  }
}

console.log(success
  ? `\n[OK] Assembly build complete — ${modules.length} modules\n`
  : `\n[ERROR] Assembly build failed\n`
);

process.exit(success ? 0 : 1);

// ============================================================================
// Generate precomputed log2 lookup table for entropy_calc.asm
// ============================================================================
function generateLog2LUT() {
  const lut = [];
  for (let i = 1; i <= 255; ++i) {
    const p = i / 256.0;
    const log2p = Math.log2(p);  // negative value
    const fixed = Math.round(-log2p * 65536);  // scale by 2^16
    lut.push(`    dd ${fixed}   ; i=${i}, log2(${i}/256) ≈ ${log2p.toFixed(6)}`);
  }

  const asmPath = path.join(__dirname, '..', 'asm', 'log2_lut_generated.asm');
  const content = [
    '; AUTO-GENERATED by scripts/build-asm.js — DO NOT EDIT',
    '; log2_fixed[i] = round(-log2(i/256) * 2^16) for i=1..255',
    '; Loaded by entropy_calc.asm for Shannon entropy computation',
    '',
    'section .rodata',
    'align 16',
    'log2_lut_generated:',
    ...lut,
    '    dd 0   ; sentinel (i=256)',
    '',
  ].join('\n');

  fs.writeFileSync(asmPath, content);
  console.log('[GEN]  log2_lut_generated.asm (255 entries)');
}
